# Generated by Django 4.1.5 on 2023-01-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_name', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=10)),
                ('beer_price', models.IntegerField()),
                ('beer_quantity', models.IntegerField()),
            ],
        ),
    ]
