# Generated by Django 4.1.5 on 2023-02-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beertype', models.CharField(max_length=100)),
                ('beername', models.CharField(max_length=100)),
                ('beerbrewery', models.CharField(max_length=100)),
                ('beerNr', models.IntegerField(max_length=100)),
                ('beerCountry', models.CharField(max_length=10, null=True)),
                ('beerAmount', models.CharField(max_length=10, null=True)),
                ('beerPercentage', models.CharField(max_length=10, null=True)),
                ('beerPrice', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
