# Generated by Django 4.1.5 on 2023-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeerInfoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beerNr',
            field=models.IntegerField(),
        ),
    ]
