# Generated by Django 4.1.5 on 2023-02-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeerInfoApp', '0002_alter_beer_beernr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='beerbrewery',
            new_name='beerBrewery',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='beername',
            new_name='beerName',
        ),
        migrations.RenameField(
            model_name='beer',
            old_name='beertype',
            new_name='beerType',
        ),
        migrations.AlterField(
            model_name='beer',
            name='beerPrice',
            field=models.DecimalField(decimal_places=2, max_digits=10000, max_length=10, null=True),
        ),
    ]
