# Generated by Django 4.1.5 on 2023-02-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeerInfoApp', '0003_rename_beerbrewery_beer_beerbrewery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breweryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='beer',
            name='beerBrewery',
        ),
        migrations.AddField(
            model_name='beer',
            name='brewery',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='CraftBeerInfoApp.brewery'),
            preserve_default=False,
        ),
    ]
