# Generated by Django 4.1.5 on 2023-02-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeerInfoApp', '0004_brewery_remove_beer_beerbrewery_beer_brewery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='brewery',
            new_name='beerBrewery',
        ),
    ]
