# Generated by Django 4.1.5 on 2023-02-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeerInfoApp', '0006_alter_beer_beerbrewery_alter_brewery_breweryname'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='beer',
            constraint=models.UniqueConstraint(fields=('beerName', 'beerNr'), name='beerNr_beerName_constraint'),
        ),
    ]
