# Generated by Django 4.1.5 on 2023-02-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CraftBeerInfoApp', '0007_beer_beernr_beername_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='brewery',
            constraint=models.UniqueConstraint(fields=('breweryName',), name='breweryName_constraint'),
        ),
    ]
